from __future__ import annotations as _annotations

from ._version import __version__
from .adapter import DataInstT, PydanticGEPAAdapter, RolloutOutputT
from .asi import (
    ASIBuilder,
    ComponentRecordSelector,
    PydanticEvalsASIBuilder,
    PydanticEvalTrajectory,
    SampleSelection,
)
from .candidates import (
    Candidate,
    CandidateComponent,
    Component,
    ComponentKind,
    InstructionsCandidate,
    SerializationMode,
)
from .compat import EvaluationBatch, GEPAAdapter
from .components import ComponentCatalog, ComponentSelector, SelectorMode
from .configuration import GEPAConfig, RunConfig
from .errors import (
    CandidateComponentError,
    CandidateInjectionError,
    EvaluationHarnessError,
    EvidenceEncodingError,
    InfrastructureError,
    InvalidScoreError,
    OptimizationDependencyError,
    PlanError,
    PydanticGEPAError,
    RunStoreError,
)
from .evaluation import (
    Attachment,
    CacheStore,
    CaseResult,
    Context,
    DataSplit,
    Evaluation,
    EvaluationConfig,
    InMemoryCache,
    RescoreResult,
    arun_rescore,
    rescore,
)
from .events import Event
from .examples import (
    EvalContextView,
    EvaluationContext,
    EvaluationOutput,
    EvaluationReasonView,
    EvaluationScalar,
    EvaluationValue,
    Example,
    Optimization,
    OptimizationBackend,
    PydanticEvaluator,
    PydanticGEPAOptimization,
    ScoreFunction,
    ScoreOutput,
    model_field_accuracy,
    optimize,
)
from .harness import PydanticEvalsHarness, run_awaitable_sync
from .injections import (
    AgentInstructionsInjection,
    CandidateContext,
    CandidateInjection,
    DerivedValueInjection,
    ModelOutputInjection,
    NoopInjection,
)
from .objectives import (
    MetricResult,
    MetricRole,
    MetricSideInfoValue,
    ObjectiveDirection,
    ScoreObjective,
)
from .optimizer import OptimizeFn, PydanticGEPAOptimizer, result_from_gepa
from .orchestration import Budget, Plan, PlanResult, Stage, StageResult
from .recorder import CandidateEvaluationRecorder, GEPAEventBridge, OptimizationEventRecorder
from .reflection import CallableReflectionModel, ReflectionModel
from .results import CandidateSummary, OptimizationResult, PydanticGEPAResult
from .runtime import Runtime
from .schema_components import (
    ModelSchemaCandidate,
    SchemaComponentTarget,
    SchemaDescription,
    ToolDefinitionView,
    ToolSchemaCandidate,
    apply_model_schema_candidate,
    apply_tool_schema_candidate,
    collect_model_components,
    collect_tool_components,
    collect_toolset_components,
    description_key,
    format_schema_path,
    iter_model_descriptions,
    iter_schema_descriptions,
    parameter_key,
    parse_schema_path,
    set_schema_description,
)

__all__ = (
    "ASIBuilder",
    "AgentInstructionsInjection",
    "Attachment",
    "Candidate",
    "CandidateComponent",
    "CandidateComponentError",
    "CandidateContext",
    "CandidateEvaluationRecorder",
    "CandidateInjection",
    "CandidateInjectionError",
    "CandidateSummary",
    "CacheStore",
    "CallableReflectionModel",
    "CaseResult",
    "Component",
    "ComponentCatalog",
    "ComponentRecordSelector",
    "ComponentKind",
    "ComponentSelector",
    "Context",
    "DataSplit",
    "DataInstT",
    "DerivedValueInjection",
    "EvalContextView",
    "EvaluationBatch",
    "EvaluationContext",
    "Evaluation",
    "EvaluationConfig",
    "EvaluationHarnessError",
    "EvidenceEncodingError",
    "EvaluationOutput",
    "EvaluationReasonView",
    "EvaluationScalar",
    "EvaluationValue",
    "Event",
    "Example",
    "GEPAAdapter",
    "GEPAConfig",
    "GEPAEventBridge",
    "InstructionsCandidate",
    "InfrastructureError",
    "InMemoryCache",
    "InvalidScoreError",
    "MetricResult",
    "MetricRole",
    "MetricSideInfoValue",
    "ModelSchemaCandidate",
    "ModelOutputInjection",
    "NoopInjection",
    "ObjectiveDirection",
    "OptimizationDependencyError",
    "OptimizationBackend",
    "Optimization",
    "OptimizationEventRecorder",
    "OptimizationResult",
    "OptimizeFn",
    "PydanticEvalTrajectory",
    "PydanticEvalsASIBuilder",
    "PydanticEvalsHarness",
    "PydanticEvaluator",
    "PydanticGEPAAdapter",
    "PydanticGEPAError",
    "PydanticGEPAOptimization",
    "PydanticGEPAOptimizer",
    "PydanticGEPAResult",
    "Plan",
    "PlanError",
    "PlanResult",
    "RolloutOutputT",
    "ReflectionModel",
    "Runtime",
    "RunConfig",
    "RunStoreError",
    "RescoreResult",
    "SchemaComponentTarget",
    "SchemaDescription",
    "ScoreObjective",
    "ScoreFunction",
    "ScoreOutput",
    "Stage",
    "StageResult",
    "Budget",
    "SampleSelection",
    "SerializationMode",
    "SelectorMode",
    "ToolDefinitionView",
    "ToolSchemaCandidate",
    "__version__",
    "apply_model_schema_candidate",
    "apply_tool_schema_candidate",
    "collect_model_components",
    "collect_tool_components",
    "collect_toolset_components",
    "description_key",
    "format_schema_path",
    "iter_model_descriptions",
    "iter_schema_descriptions",
    "model_field_accuracy",
    "optimize",
    "parameter_key",
    "parse_schema_path",
    "result_from_gepa",
    "arun_rescore",
    "rescore",
    "run_awaitable_sync",
    "set_schema_description",
)
